### PR TITLE
Remove Yarn in favor of NPM. Closes #1110

### LINKED ISSUE #1110: Add yarn audit to Travis

### PR DESCRIPTION
**Pull request by yachtcaptain23**
Submitter Checklist:

- [ ] Submitted a [ticket](https://github.com/brave-intl/publishers/issues) for my issue if one did not already exist.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [ ] Tagged reviewers.
- [ ] Integrated piwik/matomo (for code that adds new buttons).
- [ ] Addressed or ignored all brakeman warnings

Test Plan:

Reviewer Checklist:

Tests
- [ ] Adequate test coverage exists to prevent regressions

Security:
- [ ] No raw SQL -- Always prefer ActiveRecord query helpers ([more info on StackOverflow](https://stackoverflow.com/questions/41410752/rails-5-sql-injection#41452695))
- [ ] XSS is mitigated -- Avoid `html_safe` and `raw`; escape untrusted content from users and 3rd party APIs ([Rails XSS guide](https://brakemanpro.com/2017/09/08/cross-site-scripting-in-rails) and [OWASP XSS Prevention Cheat Sheet](https://www.owasp.org/index.php/XSS_(Cross_Site_Scripting)_Prevention_Cheat_Sheet))

### CODE REVIEW

**Comment by yachtcaptain23** [comment]
Going to need to follow https://itnext.io/how-to-use-webpacker-with-npm-instead-of-yarn-a8a764e3a8ab

**Comment by CoryMcDonald** [comment]
Could I ask the reasoning behind this change? I took a look at #1110 but didn't see anything written for it.

It seems like the rails community has chosen yarn as opposed to npm. Which means migrating to npm would lead to potential migration issues. In addition yarn guarantees deterministic behavior which seems preferable to npm?

**Comment by yachtcaptain23** [comment]
@CoryMcDonald Starting in npm 5, NPM is deterministic by tracking changes in package-lock.json. Our security teams urges us to use npm over yarn given the benefits of `npm audit`.

**Comment by yachtcaptain23** [comment]
FYI I used https://itnext.io/how-to-use-webpacker-with-npm-instead-of-yarn-a8a764e3a8ab

**Comment by corymcdonald** [comment]
yarn audit has been released in version v1.12.3.

Can we close this PR and stick with that?

**Comment by yachtcaptain23** [comment]
Fixed in https://github.com/brave-intl/publishers/pull/1434

**Pull request closed without merging**
