### PR TITLE
Email Instances are replaced (#3194)

### PR DESCRIPTION
**Pull request by yashsehgal**
## Pull Request Name
Removed the Email Instances of the Publisher Email Address and replaced by `community.brave.com`

#### Features
I have changed the 2 instances of the publisher's email address to the provided URL `community.brave.com`
The way I changed it is, I have replaced the `mailto:publishers@basicattentiontoken.org` link method to the provided link, in the file `public\static\js\main.11acddcf.chunk.js`

#### Pull Request Checklist

- [ ] Adequate test coverage exists to prevent regressions -- [Guide to Testing](https://guides.rubyonrails.org/testing.html)
- [ ] XSS is mitigated -- [Guide to XSS Prevention](https://guides.rubyonrails.org/security.html#cross-site-scripting-xss)
- [ ] No raw SQL -- [Guide to SQL Injection Prevention](https://guides.rubyonrails.org/security.html#sql-injection)
- [ ] UI/UX is responsive -- [Guide to Responsive UI/UX](https://developers.google.com/web/fundamentals/design-and-ux/responsive/)
- [ ] Integrated Matomo for new UI elements -- [Guide to Matomo](https://developer.matomo.org/guides/integrate-introduction)
- [ ] Passes checklist for Progressive Web App -- [Guide to PWAs](https://developers.google.com/web/progressive-web-apps/checklist)

### CODE REVIEW

**Comment by Miyayes** [comment]
Related to https://github.com/brave-intl/publishers/issues/3194

**Comment by tsmartt** [comment]
Hi @yashsehgal -- thanks for this work! To be able to completely close the ticket, we'll need redirect users to the forum in multiple places, namely, wherever we find these constants/references:

- `SUPPORT_EMAIL`
- `Rails.application.secrets[:support_email]` (or the like)

You can get a good idea by looking [here](https://github.com/brave-intl/publishers/search?q=SUPPORT_EMAIL)

It would be good to focus on [channels_helper](https://github.com/brave-intl/publishers/blob/d351200a0091e7aa28f9502f2b58526ea0978251/app/helpers/channels_helper.rb#L108), the [secrets](https://github.com/brave-intl/publishers/blob/f5d4dfbe280f1fc9631f803020c2426b840fb382/config/secrets.yml), [shared](https://github.com/brave-intl/publishers/blob/d351200a0091e7aa28f9502f2b58526ea0978251/app/views/errors/shared.html.slim), and the [english translations](https://github.com/brave-intl/publishers/blob/d351200a0091e7aa28f9502f2b58526ea0978251/config/locales/en.yml).

For updating the static home page, feel free to edit [this file](https://github.com/brave-intl/publishers/blob/d351200a0091e7aa28f9502f2b58526ea0978251/public/creators-landing/src/locale/en.js), which will then regenerate the compiled files you edited manually. You shouldn't have to edit those manually.

Let me know if you have any questions!

**Comment by yashsehgal** [comment]
> which will then regenerate the compiled files you edited manually. You shouldn't have to edit those manually.

Thanks, @tsmartt for the detailed explanation. I will follow the steps and update you accordingly.

**Comment by yachtcaptain23** [comment]
Resolved by https://github.com/brave-intl/publishers/pull/3367

**Pull request closed without merging**
