### PR TITLE
Kick off payout jobs based on selected wallet provider

### PR DESCRIPTION
**Pull request by nvonpentz**
Resolves https://github.com/brave-intl/publishers/issues/2921

### CODE REVIEW

**Comment by tsmartt** [comment]
This is great, and I'll work on integrating it next week. We need to first close a bug where if a user disconnects a wallet, it sets their selected_waller to nil, even if the wallet _type_ was not the same.

**Comment by dogweather** [comment]
@tsmartt Is there an Issue for that wallet bug?

**Comment by tsmartt** [comment]
There is now https://github.com/brave-intl/publishers/issues/3223

**Comment by tsmartt** [comment]
Closing as duplicate of https://github.com/brave-intl/publishers/pull/3238

**Pull request closed without merging**
