### PR TITLE
Only run dependabot on code that runs in production

### PR DESCRIPTION
**Pull request by tsmartt**

### CODE REVIEW

**Review by diracdeltas — CHANGES_REQUESTED** [review]
I don't think we want to suppress dev dependency warnings, since compromise of a dev/build machine can lead to compromise of production code. however i am ok with running the dev dependency audits less often if they're too noisy.

**Comment by tsmartt** [comment]
> I don't think we want to suppress dev dependency warnings, since compromise of a dev/build machine can lead to compromise of production code. however i am ok with running the dev dependency audits less often if they're too noisy.

Yes, most come from react-scripts which [recommend only reporting prod](https://github.com/facebook/create-react-app/issues/11174) dependencies.

**Comment by diracdeltas** [comment]
i'd rather just exclude individual audit errors that we know are low-risk (like regex DoS's) or force resolutions to fix the audit errors

**Comment by diracdeltas** [comment]
https://github.com/brave-intl/publishers/pull/3516

**Comment by tsmartt** [comment]
That works.

**Pull request closed without merging**
