### PR TITLE
Update node-sass to 8.0.0 

### PR DESCRIPTION
**Pull request by thypon**
## Pull Request Name

Update node-sass to 8.0.0

#### Features

Update 8.0.0

#### How To Test

1. Verify if `node-sass` works properly

#### Pull Request Checklist

- [x] Adequate test coverage exists to prevent regressions -- [Guide to Testing](https://guides.rubyonrails.org/testing.html)
- [x] XSS is mitigated -- [Guide to XSS Prevention](https://guides.rubyonrails.org/security.html#cross-site-scripting-xss)
- [x] No raw SQL -- [Guide to SQL Injection Prevention](https://guides.rubyonrails.org/security.html#sql-injection)
- [x] UI/UX is responsive -- [Guide to Responsive UI/UX](https://developers.google.com/web/fundamentals/design-and-ux/responsive/)
- [x] Integrated Matomo for new UI elements -- [Guide to Matomo](https://developer.matomo.org/guides/integrate-introduction)
- [x] Passes checklist for Progressive Web App -- [Guide to PWAs](https://developers.google.com/web/progressive-web-apps/checklist)

### CODE REVIEW

**Comment by thypon** [comment]
@SocketSecurity ignore node-sass@8.0.0

**Comment by thypon** [comment]
Weirdly since I removed and recreated `yarn.lock` it started failing the lint phase,
even if the `package.json` did not changed in any meaningful way.

**Comment by thypon** [comment]
All good, however removing the `yarn.lock` and then recreating it,
it will break the build for some reason. Something to investigate.

**Review by tsmartt — APPROVED** [review]

**Comment by tsmartt** [comment]
> it will break the build for some reason. Something to investigate.

Will investigate in a separate PR

**Pull request merged**
