### PR TITLE
Ask publishers for listing permission immediately after verification

### LINKED ISSUE #260: Ask publishers for listing permission immediately after verification
Issue for tracking #258

> Follows specs from @jenn-rhim as closely as possible:

> The dialog can only be dismissed by making a choice.
> The dialog will only appear once. This is guaranteed by setting show_verification_status to null by default, and then setting it to true or false according to the user selection.
> A blur filter is applied to the background when the dialog is displayed.
> The dialog is responsive

### PR DESCRIPTION
**Pull request by dgeb**
Instead of asking publishers for permission to be listed as verified publishers prior to verification, this change introduces a dialog that asks them for this permission _after verification_ on their first visit to the dashboard.

Follows specs from @jenn-rhim as closely as possible:

* The dialog can only be dismissed by making a choice.
* The dialog will only appear once. This is guaranteed by setting `show_verification_status` to null by default, and then setting it to `true` or `false` according to the user selection.
* A blur filter is applied to the background when the dialog is displayed.
* The dialog is responsive (see screenshots below).

In a full width window:

screen shot 2017-11-12 at 9 30 04 pm

In a narrow window:

screen shot 2017-11-12 at 9 29 54 pm

Closes #260

Submitter Checklist:

- [X] Submitted a [ticket](https://github.com/brave-intl/publishers/issues) for my issue if one did not already exist.
- [X] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [ ] Tagged reviewers.

Test Plan:

Reviewer Checklist:

Tests
- [ ] Adequate test coverage exists to prevent regressions

Security:
- [ ] No raw SQL -- Always prefer ActiveRecord query helpers ([more info on StackOverflow](https://stackoverflow.com/questions/41410752/rails-5-sql-injection#41452695))
- [ ] XSS is mitigated -- Avoid `html_safe` and `raw`; escape untrusted content from users and 3rd party APIs ([Rails XSS guide](https://brakemanpro.com/2017/09/08/cross-site-scripting-in-rails) and [OWASP XSS Prevention Cheat Sheet](https://www.owasp.org/index.php/XSS_(Cross_Site_Scripting)_Prevention_Cheat_Sheet))

### CODE REVIEW

**Comment by mrose17** [comment]
@dgeb - looks like travis is having issues...

@ayumi - can you review this PR? thanks!

**Comment by dgeb** [comment]
@mrose17 sorry, I mistakenly included an unrelated testing change which broke travis. Fixed now!

**Comment by mrose17** [comment]
no worries... at least no one posted any private keys (-;

**Comment by ayumi** [comment]
- is there a corresponding github issue for this

- for the noscript case, this patch breaks the dashboard with the invisible overlay. this is unusable.
i think we should start with a display: none overlay and show it via javascript when triggering the modal.

**Comment by mrose17** [comment]
@ayumi - i can't find an issue either. we are running "pretty quickly" on this one...

@dgeb - i share @ayumi's concerns regarding the noscript case. your thoughts/fix?

**Comment by ayumi** [comment]
@mrose17 RE: issue: To maintain project management sanity we must make issues for any work. I've created #260 to track this.

**Comment by dgeb** [comment]
@ayumi Thanks for testing with JS disabled. I've made sure that the overlay does not interfere by marking it `display: none` by default and only showing it with JS, as you suggested.

I've also updated the appearance of the noscript warning to be a little more prominent and consistent with the new look of the site.


screen shot 2017-11-13 at 3 37 21 pm

**Pull request merged**
