### PR TITLE
chore: update Webauthn config to align supported algorithms with policy

### PR DESCRIPTION
**Pull request by kdenhartog**
#### Features

This is meant to be updating the supported algorithms policy to check that the new algorithms can be used for verification. This closes https://github.com/brave/security/issues/802

#### How To Test

1. Use webauthn with an authenticator that uses one of the new algorithms

#### Pull Request Checklist

- [X] Adequate test coverage exists to prevent regressions -- [Guide to Testing](https://guides.rubyonrails.org/testing.html)
- [X] XSS is mitigated -- [Guide to XSS Prevention](https://guides.rubyonrails.org/security.html#cross-site-scripting-xss)
- [X] No raw SQL -- [Guide to SQL Injection Prevention](https://guides.rubyonrails.org/security.html#sql-injection)
- [X] UI/UX is responsive -- [Guide to Responsive UI/UX](https://developers.google.com/web/fundamentals/design-and-ux/responsive/)
- [ ] Integrated Matomo for new UI elements -- [Guide to Matomo](https://developer.matomo.org/guides/integrate-introduction)
- [X] Passes checklist for Progressive Web App -- [Guide to PWAs](https://developers.google.com/web/progressive-web-apps/checklist)

### CODE REVIEW

**Comment by kdenhartog** [comment]
@tsmartt or @thypon do either of you know a good way to generate an equivalent unit test for one of the new algorithms so that we can properly regression test this?

**Review by tsmartt — APPROVED** [review]

**Comment by kdenhartog** [comment]
Was thinking about another one of these [test response](https://github.com/brave-intl/publishers/blob/2b1da8a703bab908ab4f307c31d33b272d04597b/test/controllers/u2f_authentications_controller_test.rb#L7) @thypon since it looks like we've been able to generate them before, but I couldn't figure out how.

**Comment by thypon** [comment]
I think this is real data coming from a real token, saved there; the check is then stubbed to always return `true` on verify, so it's just a placeholder.

Not sure if we can easily test them or if we want to test them programmatically though. Last word on @tsmartt , since I feel this is an improvement over the status quo either way, with the test or without them.

**Comment by tsmartt** [comment]
We can add a test to verify the config is correct, that should be easier. And we can trust the library's implementation.

**Comment by tsmartt** [comment]
I can do early next week if you cannot do it sooner.

**Comment by OAuthBringer** [comment]
@kdenhartog You should be able to do a trivial assertion against the Webauthn configuration in a spec.

In irb you can access the allowed algorithms via `WebAuthn.configuration.algorithms`

So you can explicitly check to assert that the config contains/does not contain whatever you are looking to test

So something like `test/webauthn_config_test.rb`

`assert WebAuthn.configuration.algorithms.include?("PS512")`
`assert !WebAuthn.configuration.algorithms.include?("RS256")

FWIW you can also complete override the allowed algorithms with

`config.algorithms = [only, the, ones, I, want]`

**Comment by kdenhartog** [comment]
Sounds like an easy way to handle this to me! I can add that today

**Comment by OAuthBringer** [comment]
@thypon this appears to be failing due to a login failure for semgrep?

**Comment by OAuthBringer** [comment]
@kdenhartog I'm not sure why the semgrep job keeps failing.  I'm wondering if it's because the branch is forked?

**Comment by tsmartt** [comment]
Yes, if you reopen this as a branch on the main repo, it has access to secrets and should pass.

**Review by tsmartt — APPROVED** [review]

**Comment by kdenhartog** [comment]
Ahh ok. I think at the time when I originally opened I didn't have the proper access for that and so just forked to handle this. Looks like we managed to get it through now and going forward I'll push branches directly to origin remote rather than a forked remote.

**Pull request merged**
