### PR TITLE
Improve the landing page on mobile.

### LINKED ISSUE #199: Optimize the mobile view: responsive text size and form layout to the viewport
All publisher pages are not responsive on mobile.  
1. body copy is too small to read
2. Text fields and button are side-by-side
3. Some headings are too big

Example screenshot: (scale down to show a realistic reading view)
screen shot 2017-10-20 at 11 45 01 am

1: Need to fix the meta tag for the viewport, scale currently set at 0.6: change to 1
2: Stack text fields and button: i.e. one element per row -- for the most cases (99%), do not try to keep a text field and a button on the same row even if that is the layout for the desktop.
3: proportionally scale down headings in the media query per break points

### PR DESCRIPTION
**Pull request by mixonic**
Closes #199. The goal is to improve the mobile responsiveness of the landing page. This PR does not attempt to improve the responsiveness of the site as a whole, only the landing page.

brave-responsive

Test Plan:

- Run the branch with your browsers's responsive layout emulation.

Reviewer Checklist:

Tests
- [ ] Adequate test coverage exists to prevent regressions

Security:
- [ ] No raw SQL -- Always prefer ActiveRecord query helpers ([more info on StackOverflow](https://stackoverflow.com/questions/41410752/rails-5-sql-injection#41452695))
- [ ] XSS is mitigated -- Avoid `html_safe` and `raw`; escape untrusted content from users and 3rd party APIs ([Rails XSS guide](https://brakemanpro.com/2017/09/08/cross-site-scripting-in-rails) and [OWASP XSS Prevention Cheat Sheet](https://www.owasp.org/index.php/XSS_(Cross_Site_Scripting)_Prevention_Cheat_Sheet))

### CODE REVIEW

**Comment by alexwykoff** [comment]
At first glance, there is too much whitespace at the top and perhaps the header text didn't scale quite enough. 
Also not sure about missing CTA on immediate view. 
@jenn-rhim should be able to elaborate on needs here wrt this PR

**Comment by jenn-rhim** [comment]
1. @mixonic can you send me a static screenshot of the mobile view? 

2. responsiveness looks good.

3. let's define the text size of the title (**Brave Payments**) to 0.6 in the media query for mobile view port sizes. i can't tell the body copy size whether it's readable or not. static screenshot would be helpful.

**Comment by mixonic** [comment]
@jenn-rhim happy to pair on this. I worry screenshots are going to be a very low-velocity way for you to review the change and make suggestions. There are a number of breakpoints at play.

**iPhone 7**

screen shot 2017-11-20 at 3 09 28 pm

screen shot 2017-11-20 at 3 14 07 pm


**iPad**

screen shot 2017-11-20 at 3 10 28 pm

**Laptop**

screen shot 2017-11-20 at 3 10 59 pm

Can you say more about the font size? Font size here is not relative (maybe you meant `0.6em`?), it is in `px`: https://github.com/mixonic/publishers/blob/199-mobile-friendly/app/assets/stylesheets/application/static.sass#L44 `h1` is currently `48px`. Making it `48px * 0.6` would be `28px` which is a bit smaller than the `Welcome to` at `32px`.

**Comment by jenn-rhim** [comment]
@mixonic Yes, I meant em. I only concern about mobile devices with the high resolution/pixel density. If your screenshot is an accurate display for iphone 7, i'd reduce the title size so it fits in one line: maybe 0.8em so it's bigger than welcome to.

if i look at the live page on my mobile, all the type looks tiny- can't read it (except title). based on your screenshot, i assume that's been addressed?

**Pull request merged**
