### PR TITLE
Add note on dashboard for when payout is in progress

### LINKED ISSUE #1594: add a additional state for "Next Deposit Date:" display - "Payout In Progress"
when performing the monthly payout we often get user confusion as they may see their balances paid out in part, without the balance on their dashboard being updated. this is an artifact of the payout procedure.

it might be helpful if we were to have an alternate state for the "Next Deposit Date:" bit of text - whereby an admin can set a payout as "in progress" so that users know payout is ongoing

### PR DESCRIPTION
**Pull request by nvonpentz**
Resolves #1594 

image

Submitter Checklist:

- [ ] Submitted a [ticket](https://github.com/brave-intl/publishers/issues) for my issue if one did not already exist.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [ ] Tagged reviewers.
- [ ] Integrated piwik/matomo (for code that adds new buttons).
- [ ] Addressed or ignored all brakeman warnings

Test Plan:

Reviewer Checklist:

Tests
- [ ] Adequate test coverage exists to prevent regressions

Security:
- [ ] No raw SQL -- Always prefer ActiveRecord query helpers ([more info on StackOverflow](https://stackoverflow.com/questions/41410752/rails-5-sql-injection#41452695))
- [ ] XSS is mitigated -- Avoid `html_safe` and `raw`; escape untrusted content from users and 3rd party APIs ([Rails XSS guide](https://brakemanpro.com/2017/09/08/cross-site-scripting-in-rails) and [OWASP XSS Prevention Cheat Sheet](https://www.owasp.org/index.php/XSS_(Cross_Site_Scripting)_Prevention_Cheat_Sheet))

### CODE REVIEW

**Comment by nvonpentz** [comment]
Cool, I will be adding support for a flag and will also remove 'Next deposit date..' text when payout is in progress.

For the flag it sounds like we want something that's automatically set at the beginning of the month then manually unset when the payout is completed.  Sounds like redis is a good choice.

**Comment by corymcdonald** [comment]
Do you think we should separate out the pending amount and the amount that the user is going to get paid? I think that could be confusing as their balance could increment but they wouldn't get paid for that amount

**Comment by nvonpentz** [comment]
That could be useful.  The publisher may infer on there own that the donations received while the payout is in progress will be deposited next month.

For this next month's payout I think this should suffice.

**Comment by nvonpentz** [comment]
Updated dashboard looks like
image

**Pull request merged**
